spring:
  datasource:
    url: jdbc:mysql://localhost:23302/external_generated_id
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
